image: docker:stable

stages:
- build

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

variables:
  DOCKER_DRIVER: overlay2
  
build:
  stage: build
  script:
    - docker build -t registry.gitlab.com/tedyst/scraper:latest .
    - docker push registry.gitlab.com/tedyst/scraper:latest