image: docker:stable

stages:
- build
- lansare

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

variables:
  DOCKER_DRIVER: overlay2
  
build:
  stage: build
  script:
    - docker build -t registry.gitlab.com/tedyst/spotifybot:latest .
    - docker push registry.gitlab.com/tedyst/spotifybot:latest
    
lansare:
  stage: lansare
  script:
    - docker stop spotifybot_1 || true
    - docker rm spotifybot_1 || true
    - docker run --name spotifybot_1 -d --restart always
      -v /var/spotifybot/audio_cache/:/usr/src/musicbot/audio_cache/
      -v /var/spotifybot/data/:/usr/src/musicbot/data/
      registry.gitlab.com/tedyst/spotifybot:latest