version: '3'

services:
  scraper:
    build: 
      context: ./
    container_name: scraper
    restart: always
    networks:
      - default
    environment:
      - PYTHONUNBUFFERED=1



networks:
  default:
    external:
      name: web