version: "3"

services:
  scraper:
    build:
      context: ./
    restart: always
    networks:
      - default
    environment:
      - PYTHONUNBUFFERED=1

networks:
  default:
    external:
      name: web
