version: '3'

services:
  reverse-proxy:
    image: scraper
    build: 
      context: ./
    container_name: scraper
    networks:
      - default
    restart: always

networks:
  default:
    external:
      name: web