use_elasticsearch = True
elasticsearch_host = "elasticsearch"
elasticsearch_port = 9200
links = ["https://www.emag.ro/routere_wireless/p1/c",
         "https://www.emag.ro/routere_wireless/p2/c",
         "https://www.emag.ro/routere_wireless/p3/c",
         "https://www.emag.ro/routere_wireless/p4/c",
         "https://www.emag.ro/routere_wireless/p5/c",
         "https://www.emag.ro/procesoare/p1/c",
         "https://www.emag.ro/procesoare/p2/c",
         "https://www.emag.ro/procesoare/p3/c",
         "https://www.emag.ro/placi_baza/p1/c",
         "https://www.emag.ro/placi_baza/p2/c",
         "https://www.emag.ro/placi_baza/p3/c",
         "https://www.emag.ro/placi_baza/p4/c",
         "https://www.emag.ro/placi_baza/p5/c",
         "https://www.emag.ro/placi_baza/p6/c",
         "https://www.emag.ro/placi_baza/p7/c",
         "https://www.emag.ro/placi_baza/p8/c",
         "https://www.emag.ro/memorii/filter/tip-memorie-f5,ddr4-v10954/p1/c",
         "https://www.emag.ro/memorii/filter/tip-memorie-f5,ddr4-v10954/p2/c",
         "https://www.emag.ro/memorii/filter/tip-memorie-f5,ddr4-v10954/p3/c",
         "https://www.emag.ro/memorii/filter/tip-memorie-f5,ddr4-v10954/p4/c",
         "https://www.emag.ro/memorii/filter/tip-memorie-f5,ddr4-v10954/p5/c",
         "https://www.emag.ro/memorii/filter/tip-memorie-f5,ddr4-v10954/p6/c",
         "https://www.emag.ro/placi_video/p1/c",
         "https://www.emag.ro/placi_video/p2/c",
         "https://www.emag.ro/placi_video/p3/c",
         "https://www.emag.ro/placi_video/p4/c",
         "https://www.emag.ro/placi_video/p5/c",
         "https://www.emag.ro/placi_video/p6/c",
         "https://www.emag.ro/placi_video/p7/c",
         "https://www.emag.ro/placi_video/p8/"]
